# -*- coding: utf-8 -*-
"""Exercise1-Question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vnu609Pm4FRDGVlTyrZvg14LTf7xt_Ak
"""

Exercise 1 Question 1:
Write a program which reads two integer values. If the first number is less than the
second, print the message "First number is less than the second".
If the second is less than the first, print the message "Second number is less than the
first".
If the numbers are equal, print the message "The numbers are equal".

print("######################################################")
print("Program to print which is the less number")
print("######################################################")

while True:
      x=int(input("Please enter the first integer"))
      y=int(input("Please enter the second interger"))
      if x<y:
            print( x,"The first number is less than the second number")
      elif y<x:
            print( y,"The Second number is less than the first number")
      elif x==y:
            print("The numbers are equal")

      user_input=input("Do you want to continue yes/no").lower()
      if user_input=='no' or user_input=='n' or user_input=='quit':
          break

print("End of Program")
print("######################################################")