# -*- coding: utf-8 -*-
"""Exercise2-Question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j6YhnVeeLNrQRXkp777uDD9SR4dfyIu_
"""

Create a console application which will ask the user to enter a number between 0 and 1000. The
program will then determine if the number entered is an even number or not. If the number
entered is an even number show the message “The number you entered is even”. If the number
entered is an odd number show the message “The number you entered is odd”. If the user
enters an invalid number show the message “You entered an invalid number”. In this case an
invalid number is less than 1 or greater than 1000.

print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("WELCOME TO A CONSOLE PROGRAM TO FIND EVEN OR ODD NUMBERS")
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
while True:
  x=float(input("Please enter a Number between 0 and 1000"))
  if(x<1 or x>1000):
    print("Please Enter a Number within the Valid Range of 0 to 1000")
  elif(x%2==0):
    print("The number you enetered is Even!")
  elif (x%2!=0):
    print("The number you enetered is Odd!")

  user_input=input("Do you want to try any other number? Yes/No").lower()
  if user_input=='NO' or user_input=='n' or user_input=='no':
    break
print("++++++++++++++++++++++++++++++++++++++++")
print("Thank you for using the console program")
print("++++++++++++++++++++++++++++++++++++++++")