# -*- coding: utf-8 -*-
"""Exercise1-Question 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVOJcoWkeXDBpa6glDuxN76_3ki4n_Re
"""

Write a program that prompts the user to enter age. If age of the user is equal to or
greater than 18, then the proram displays “You are eligibel to vote”. Otherwise the
program displays “You cannot vote”.

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("Voting Eligibility")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

while True:
      x=int(input("Print Enter the Age of a Person"))

      if x>=18:
         print("You are eligible to Vote")
      else:
         print("You cannot Vote")


      user_input=input("Do you want to continue yes/no").lower()
      if user_input=='no' or user_input=='quit':
          break
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("Thank you for checking your eligibility")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")