# -*- coding: utf-8 -*-
"""Exercise1-Question_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJidkGEIcCCoe97fau6Xz3bff4npY8No
"""

Write a program to input a salary from the user and determine how much tax
someone should pay according to the following rules:
People pay no tax if they earn up to €10,000. They pay tax at the rate of 20% on the
amount they earn over €10,000 but up to €50,000. They pay tax at 40% on any money
they earn over €50,000.

print("**********************************************************************")
print("Tax Slabs for MyCompany")
print("**********************************************************************")

while True:
          salary=float(input("Enter the Salary you want me to calculate the tax slab for"))
          if salary<=10000.00:
            print("Tax = 0 You are ALLOWED NOT TO PAY ANY TAX, Enjoy!!!")
          elif salary>10000.00 and salary<=50000.00:
            print("You are supposed to pay €",(salary-10000)*0.20,"tax on your payment")
          elif salary>50000.00:
            print("You are supposed to pay €",((40000*0.2)+((salary-50000)*0.40)),"tax on your payment")

          user_input=input("Do you want to continue checking for any other input???").lower()
          if user_input=='no' or user_input=='quit' or user_input=='n':
            break

print("We look forward to seeing you back!!! ")
print("**********************************************************************")