# -*- coding: utf-8 -*-
"""Exercise1-Question3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdNGDbYM4tfxrEbaTf2FRQmPDF6bg5-6
"""

The Young and Beautiful Travel Company restricts its clients to ages between 18 and 30.
Write a program to input a client's age and test whether they are eligible to go on
vacation with the company or not.

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("WELCOME TO THE YOUNG & BEAUTIFUL TRAVEL COMPANY")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
while True:
          x=float(input("Input your age to check if you are allowed to to come"))
          if x>=18.0 and x<=30.0:
              print("You are allowed to come, YAY!!!!")
          else:
              print("I am so sorry your age doesn't allow us to take you in")

          user_input=input("Do you want to check anyone else's age? Y/N").lower()
          if user_input=='no' or user_input=='quit' or user_input=='n':
              break
print("See you soooooooooooon")