# -*- coding: utf-8 -*-
"""Exercise1_Question_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Ae9aWR9GL6Zg697E-P78GtWLKBdHpFM
"""

Write a program that prompts the user for either 1, 2, 3 or 4.
In your python code you will need to print out what 1, 2, 3 and 4 correspond to using
below:
1 = diamonds, 2= hearts, 3= clubs and 4 = spades respectively.

print("************************************")
print("Welcome to the Dictionary program")
print("************************************")
while True:

          x = int(input("Enter your option from the options choosing 1,2,3 or 4"))
          if x==1:
            print("You opted for 1: DIAMONDS")
          elif x==2:
            print("You opted for 2= HEARTS")
          elif x==3:
            print("You opted for 3= CLUBS")
          elif x==4:
            print("You opted for 4= SPADES")
          else:
            print("You have not entered the correct value")

          user_input=input("Do you want to continue? Yes or No or Quit?").lower()
          if user_input =='no' or user_input=='Quit' or user_input=='quit':
            break
print("*****************************************")
print("It was fun playing with you, visit again")
print("*****************************************")