# -*- coding: utf-8 -*-
"""Exercise2-Question3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FrjhvdCG5a2ZDwOtv2hbm-HqI0kTN4Ul
"""

Write a program that reads three edges a, b and c for a triangle and computes the perimeter if
the input is valid. Otherwise, display that the input is invalid. The input is valid if the sum of
every pair of two edges is greater than the remaining edge (perimeter = a+ b +c).

print("****************************************************")
print("Program to calculate the perimeter of the triangle")
print("****************************************************")
while True:
  a=float(input("Enter the length of 1st side of the triange")) # here we take the input of all three sides of the triangle
  b=float(input("Enter the length of 2nd side of the triange"))
  c=float(input("Enter the length of 3rd side of the triange"))
  if(a+b>c and a+c>b and b+c>a):  #this is the logic of the code.
    perimeter=a+b+c
    print("The perimeter is valid for the given sides of the Triangle")
  else:
    print("The perimeter is not valid for the given sides of the Traiangle. As the sides of the triangle are not matching")

  user_input=input("Do you want to continue to check with any other triangle? YES/No ?").lower()
  if user_input=='No' or user_input=='no' or user_input=='q' or user_input=='quit':
    break
print("****************************************************************")
print("Thank you for chosing the program for calculating the perimeter")
print("****************************************************************")