# -*- coding: utf-8 -*-
"""Exercise 1_Question_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gWhIEH7-q9YCY0oIzVea1050gc0tLrb0
"""

6. Write a program which displays a menu to the user. The menu should look similar to the
following:
Welcome to the SimpleCacl
Press 1 to add two numbers
Press 2 to subtract two numbers
Press 3 to divide two numbers
Press 4 to multiple two numbers
Read in the selection from the user and then ask the user for two numbers.
Print the result to the user.

print("*******************************")
print("WELCOME TO A SIMPLE CALCULATOR")
print("*******************************")
print("Press 1 to add two numbers")
print("Press 2 to subtract two numbers")
print("Press 3 to divide two numbers")
print("Press 4 to multiple two numbers")
while True:
  choice=int(input("Enter your choice : "))
  x=float(input("Enter the first number"))
  y=float(input("Enter the second number"))
  if choice==1:
    print("The addition of ",x,"&",y, "is : ",x+y)
  elif choice==2:
    print("The subtraction of",x,"&",y, "is: ",x-y)
  elif choice==3:
    print("The division of",x,"&",y, "is: ",x/y)
  elif choice==4:
    print("The multiplication of",x,"&",y, "is: ",x*y)

  user_input=input("Do you want to continue with any other numbers? - Yes/Quit?").lower()
  if user_input=='no' or user_input=='Quit' or user_input=='quit' or user_input=='n' or user_input=='q':
    break
print("*******************************")
print("See you soon")
print("*******************************")