# -*- coding: utf-8 -*-
"""Week1Exercise2-Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

x=int(input("Enter Time in seconds "))
min=int(x/60)
sec=int(x%60)
print("The time in minutes is : ",min, ".mins And ", sec, ".Seconds")