# -*- coding: utf-8 -*-
"""Week1Exercise2-Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

num1=int(input("Enter the first number:"))
num2=int(input("Enter the second number:"))
num=num1+1
sum=num+num2
print("The sum of increamented value from 1st interger and second value is :",sum)