# -*- coding: utf-8 -*-
"""Week1Exercise2-Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

print("Enter the value of 'a' and 'b' for a(b^2) equation")
a=int(input("Enter integer for a "))
b=int(input("Enter integer for b "))
mul=a*(b**2)
print("The value of the expression is: ", mul)