# -*- coding: utf-8 -*-
"""Week1Exercise2-Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

expression=((3.5*4)/2)-2.5
print("The value of the expression is: ",expression)