# -*- coding: utf-8 -*-
"""Week1Exercise2-Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

print("Student 1's marks are 44")
print("Student 2's marks are 51")
mark1=44
mark2=51
avg=float((mark1+mark2)/2)
print("Average marks: ",avg)