# -*- coding: utf-8 -*-
"""Week1Exercise2-Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

a=int(input("enter A: "))
b=int(input("enter B: "))
c=int(input("enter C: "))
d=int(input("enter D: "))
r=int(input("enter R: "))
expression=((4/(3*(r+34)))-(9*(a+(b*c)))+3+((d*(2+a))/(a+(b*d))))
print("Expression result: ",expression)