# -*- coding: utf-8 -*-
"""Week1Exercise2-Q7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19as_zlXz2-D7VMsWGWrONvVdIe8_iMML
"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
gross_pay = float(input("Enter your gross pay: "))
tax_rate = float(input("Enter your tax rate (e.g., 0.2 for 20%): ")) #NOTICE THE DECIMAL WE ARE ENTERING for TAX RATE which is in percentage

# Below is the calculation for NET PAY.
net_pay = gross_pay * (1 - tax_rate)

# Display results
print(f"Name: (name)",name)
print(f"Age: (age)",age)
print(f"Gross Pay:€",gross_pay)
print(f"Tax Rate:",tax_rate*100,"%")
print(f"Net Pay:€",net_pay)